Repository TeamZOOC/ZOOCZOOCBBANGBBANG, pull requests merged in 2023-01, with the labels that each got.

#2 chore(bot-setting): create auto_assign.yml
  .github/auto_assign.yml
Labels: size/XS

#3 chore(pr_template): Create PR Template
  .github/pull_request_template.md
Labels: size/S

#4 Ci/lint build check
  .github/workflows/branch_push_builder.yml
  .github/workflows/pr_builder.yml
  app/src/androidTest/java/org/sopt/zooczoocbbangbbang/ExampleInstrumentedTest.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/ServiceFactory.kt
  app/src/test/java/org/sopt/zooczoocbbangbbang/ExampleUnitTest.kt
  build.gradle
Labels: size/L

#8 Feat/5 bottom navigation
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/MainActivity.kt
  app/src/main/res/color/selector_menu.xml
  app/src/main/res/drawable/bg_bottom_navigation.xml
  app/src/main/res/drawable/circle_fab.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/rect_radius_24_top.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/menu_bottom_navi.xml
  app/src/main/res/values/themes.xml
Labels: size/L

#10 Feat/#6/load image
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/MissionFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordFragment.kt
  app/src/main/res/drawable/ic_record_close_24.xml
  app/src/main/res/drawable/img_record_photo_24.xml
  app/src/main/res/drawable/shape_green_radius_20.xml
  app/src/main/res/drawable/shape_record_grey_radius_18.xml
  app/src/main/res/drawable/shape_record_white_radius_15.xml
  app/src/main/res/drawable/shape_record_white_radius_24.xml
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#15 Feat/7 mypageview
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/mypage/ResponseMembersDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/CommentersAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/LayoutManagerType.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MemberInfo.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MemberTestViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MemberViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MyCustomDialogInterface.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MyPageFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MyPageMemberAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MyPagePetAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MyPofileEdityActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MyProfileEditCustomDialog.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/PetInfo.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/PetTestViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordDoneActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/callExt.kt
  app/src/main/res/drawable-v24/myprofile_bg_btn_edit.xml
  app/src/main/res/drawable-v24/myprofile_bg_profile.xml
  app/src/main/res/drawable/bg_edit_nickname.xml
  app/src/main/res/drawable/ic_btn_recycler_add_pet.xml
  app/src/main/res/drawable/ic_mypage_edit_profile_back.xml
  app/src/main/res/drawable/ic_mypage_edit_profile_camera.xml
  app/src/main/res/drawable/ic_round_radius_18.xml
  app/src/main/res/drawable/ic_round_radius_21.xml
  app/src/main/res/drawable/ic_shape_round.xml
  app/src/main/res/drawable/img_mypet.jpg
  app/src/main/res/drawable/img_myprofile.jpg
  app/src/main/res/drawable/mypage_member.jpg
  app/src/main/res/drawable/separator_color.xml
  app/src/main/res/drawable/vector_912.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page_edit_profile.xml
  app/src/main/res/layout/custumdialog_edit_photo.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_mypage_recycler_btn_pets_add.xml
  app/src/main/res/layout/item_mypage_recycler_members.xml
  app/src/main/res/layout/item_mypage_recycler_pets.xml
  app/src/main/res/values/themes.xml
Labels: size/XXL

#21 Feat/#11/registerview
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/Choose2PetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/Choose3PetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/Choose4PetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/FourSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/FourSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/MissionFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/ThreeSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/ThreeSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/TwoSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/TwoSelectorPetViewModel.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/shape_round_green.xml
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/layout/activity_record_done.xml
  app/src/main/res/layout/fragment_four_selector_pet.xml
  app/src/main/res/layout/fragment_three_selector_pet.xml
  app/src/main/res/layout/fragment_two_selector_pet.xml
Labels: size/XL

#18 Feat/#14 missionview
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/MissionFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/MissionFragmentStateAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/MissionViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/MissionViewPagerFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordFragment.kt
  app/src/main/res/drawable/shape_green_radius_47.xml
  app/src/main/res/drawable/shape_grey_radius_47.xml
  app/src/main/res/drawable/shape_rec_white2_radius_12.xml
  app/src/main/res/drawable/shape_record_white_radius_24.xml
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/layout/fragment_four_selector_pet.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_mission_view_pager.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_three_selector_pet.xml
  app/src/main/res/layout/fragment_two_selector_pet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#31 feat(animation): 홈에서 디테일뷰로의 애니메이션 전환을 자연스럽게
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/ArchivePostingAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/ArchivePostingViewHolder.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/data/RecordTransportData.kt
  app/src/main/res/layout/activity_detail.xml
Labels: size/L

#33 Feat/32 alarm
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/AuthInterceptor.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/alarm/ResponseAlarmDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/alarm/AlarmActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/alarm/AlarmAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/alarm/AlarmViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeFragment.kt
  app/src/main/res/drawable/ic_back_arrow_grey.xml
  app/src/main/res/layout/activity_alarm.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_alarm.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#35 Feat/34 detail
  app/build.gradle
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/alarm/AlarmActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/Direction.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/ArchivePostingViewHolder.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/PetAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/data/RecordTransportData.kt
Labels: size/L

#36 Feat/34 detail
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/MainActivity.kt
  settings.gradle
Labels: size/M

#26 [Feat/onboarding] onboarding 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/App.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/BindingAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/Onboarding.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingProgress.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingStep.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingType.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterFormAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterFormListener.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/model/PetUiModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/end/OnboardingEndFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/invitation/InvitationAfterFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/invitation/InvitationBeforeFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/join/JoinFamilyFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/join/JoinFamilyViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/profile/CompleteProfileFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/profile/ProfileSelectFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/profile/ProfileSelectViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/profile/RoleInputFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/profile/RoleInputViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/AppCompatActivityExt.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/Event.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/NonNullLiveData.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/NonNullMutableLiveData.kt
  app/src/main/res/color/selector_edit_text_under_line.xml
  app/src/main/res/drawable/ic_pet_add.xml
  app/src/main/res/drawable/ic_pet_cancel.xml
  app/src/main/res/drawable/img_invitation.xml
  app/src/main/res/drawable/img_onboarding_code.xml
  app/src/main/res/drawable/img_onboarding_end.xml
  app/src/main/res/drawable/img_select_profile_image.xml
  app/src/main/res/drawable/onboarding_profile_complete_image.xml
  app/src/main/res/drawable/onboarding_progressbar.xml
  app/src/main/res/drawable/rect_radius_24_border_light_grey.xml
  app/src/main/res/drawable/selector_input_code.xml
  app/src/main/res/drawable/selector_input_pet_name.xml
  app/src/main/res/drawable/shape_green_radius_47_1.xml
  app/src/main/res/drawable/shape_white_circle.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/fragment_onboarding_end.xml
  app/src/main/res/layout/fragment_onboarding_input_code.xml
  app/src/main/res/layout/fragment_onboarding_invitation_share_link.xml
  app/src/main/res/layout/fragment_onboarding_invitation_share_link_after.xml
  app/src/main/res/layout/fragment_onboarding_pet_register.xml
  app/src/main/res/layout/fragment_onboarding_profile_complete.xml
  app/src/main/res/layout/fragment_onboarding_profile_selector.xml
  app/src/main/res/layout/fragment_onboarding_role_input.xml
  app/src/main/res/layout/item_onboarding_pet_register.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: size/XXL

#41 Feat/37 kakao login
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/ZoocApplication.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/local/ZoocStorage.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/AuthInterceptor.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/auth/ResponseSignUpDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/common/Comment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/home/response/ResponseTotalRecordsDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/test/Comment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/test/Data.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/test/Record.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/test/TempData.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/auth/AuthViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/auth/SignInActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/auth/SignUpCompleteActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/auth/SplashActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/ArchivePostingAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/ArchivePostingViewHolder.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/CommentersAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/PetAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/data/ArchivePostingData.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_kakao_login.xml
  app/src/main/res/drawable/ic_splash_logo.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up_complete.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#40 Feat/#22 multipart
  app/build.gradle
  app/src/main/java/org/sopt/zooczoocbbangbbang/App.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/ServiceFactory.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/common/Pet.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/record/RequestRecordDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/record/ResponseMissionDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/entity/record/ResponsePetInfoDto.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/CommentViewHolder.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/mypage/MemberViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/CustomDialog.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/RecordViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/daily/RecordFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/daily/RecordViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionFragmentStateAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionViewPagerFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionViewPagerViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/FourSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/FourSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/RecordDoneActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/ThreeSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/ThreeSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/TwoSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/TwoSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/ContentUriRequestBody.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/CustomAlertDialog.kt
  app/src/main/res/layout/activity_record.xml
  app/src/main/res/layout/activity_record_done.xml
  app/src/main/res/layout/fragment_four_selector_pet.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_mission_view_pager.xml
  app/src/main/res/layout/fragment_record.xml
  app/src/main/res/layout/fragment_three_selector_pet.xml
  app/src/main/res/layout/fragment_two_selector_pet.xml
  app/src/main/res/values/dimens.xml
  build.gradle
Labels: size/XXL

#44 Feat/inflate onboarding register pet
  app/src/main/java/org/sopt/zooczoocbbangbbang/App.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/OnboardingRepository.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/local/ZoocStorage.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/Onboarding.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterFormAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterFormListener.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/PetRegisterViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/create/model/PetUiModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/onboarding/invitation/InvitationBeforeFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_onboarding_invitation_share_link.xml
  app/src/main/res/layout/fragment_onboarding_pet_register.xml
  app/src/main/res/layout/fragment_onboarding_profile_complete.xml
  app/src/main/res/layout/item_onboarding_pet_register.xml
Labels: size/L

#46 Feat/#22 multipart
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/daily/RecordViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/mission/MissionViewPagerFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/FourSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/FourSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/ThreeSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/ThreeSelectorPetViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/TwoSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/TwoSelectorPetViewModel.kt
Labels: size/L

#47 Feat/43 last dance
  app/src/main/java/org/sopt/zooczoocbbangbbang/data/remote/api/ZoocService.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/detail/DetailViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/HomeViewModel.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/home/adapter/ArchivePostingAdapter.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/RecordDoneActivity.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/ThreeSelectorPetFragment.kt
  app/src/main/java/org/sopt/zooczoocbbangbbang/presentation/main/record/register/TwoSelectorPetFragment.kt
Labels: size/M
